# Generated by Django 6.0.5 on 2026-06-02 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_especialidades_medicos_pacientes_medico_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados_cita',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.pacientes')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='citas.estados_cita')),
            ],
        ),
        migrations.CreateModel(
            name='auditoria_citas',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.citas')),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medicos')),
            ],
        ),
        migrations.AddField(
            model_name='citas',
            name='id_horario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.horarios'),
        ),
        migrations.AddConstraint(
            model_name='horarios',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_hora_fin_mayor'),
        ),
        migrations.AlterUniqueTogether(
            name='horarios',
            unique_together={('id_medico', 'fecha', 'hora_inicio', 'hora_fin')},
        ),
    ]
