# Generated by Django 6.0.5 on 2026-06-02 07:39

from django.db import migrations


def poblar_estados(apps,schema_editor):
    estados_cita=apps.get_model('citas','estados_cita')
    estados=['pendiente','confirmada','realizada','cancelada','no_asistio']
    for e in estados:
        estados_cita.objects.create(nombre=e)

class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_estados_cita_citas_auditoria_citas_horarios_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_estados),
    ]
