# Generated by Django 6.0.5 on 2026-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_usuario_bloqueado_hasta_usuario_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='eps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
